### ISSUE TITLE
IE Specific CSS for Cards

### ISSUE THREAD

**Issue by lucasbmenezes** [gwtbootstrap3/gwtbootstrap3-extras#90]
Card (org.gwtbootstrap3.extras.card.Card) does not flip as expeted in IE11, it does not show the "back" face, only front face mirrored.

Even in showcase it does not work, just open on IE http://gwtbootstrap3.github.io/gwtbootstrap3-demo/#card and try to flip it: it'll show mirrored.

**Comment by jgodi** [comment]
This is because IE doesn't fully support the transform property. A lot of custom CSS will have to be written for this to work in IE. If you can submit a PR for this that would be great!

**Comment by mdavis95** [comment]
This seems to be the fix for IE10+:
http://davidwalsh.name/css-flip

**Comment by payammeyer** [comment]
I can confirm that the following CSS addition works for us in IE 10+:

```css
.flip-container {
    perspective: 1000;
    transform-style: preserve-3d;
}

.flip-container.flipped .back {
    transform: rotateY(0deg);
}

.flip-container.flipped .front {
    transform: rotateY(180deg);
}

.flip-container, .front, .back {
    width: 100%;
    height: 100%;
}

.flipped {
    transition: 0.6s;
    transform-style: preserve-3d;
    position: relative;
}

.front, .back {
    backface-visibility: hidden;
    transition: 0.6s;
    transform-style: preserve-3d;

    position: absolute;
    top: 0;
    left: 0;
}

.front {
    z-index: 2;
    transform: rotateY(0deg);
}

.back {
    transform: rotateY(-180deg);
}

.horizontal.flip-container {
    position: relative;
}

.horizontal .back {
    transform: rotateX(180deg);
}

.horizontal.flip-container.flipped .back {
    transform: rotateX(0deg);
}

.horizontal.flip-container.flipped .front {
    transform: rotateX(180deg);
}
```
